#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import json
import re
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from PIL import Image


def load_prepare_summary(path: Path) -> dict:
    if not path.exists():
        raise FileNotFoundError(f"prepare summary not found: {path}")
    data = json.loads(path.read_text())
    if int(data.get("matched_frames", 0)) <= 0:
        raise RuntimeError(f"prepare summary has no matched chin frames: {path}")
    if int(data.get("source1_points_in_merged", 0)) <= 0:
        raise RuntimeError(f"prepare summary has no source_id=1 points in merged cloud: {path}")
    if int(data.get("duplicate_chin_reuse", 0)) != 0:
        raise RuntimeError(f"prepare summary reports duplicate chin reuse: {data.get('duplicate_chin_reuse')}")
    return data


def latest_pose_rows(log: str) -> list[tuple[int, float, float, float]]:
    pose_re = re.compile(r"kf\s+(\d+), pose:\s+([-+0-9.eE]+)\s+([-+0-9.eE]+)\s+([-+0-9.eE]+)")
    poses = [(int(m.group(1)), float(m.group(2)), float(m.group(3)), float(m.group(4))) for m in pose_re.finditer(log)]
    final = []
    seen = set()
    for row in reversed(poses):
        if row[0] in seen:
            continue
        seen.add(row[0])
        final.append(row)
    final.reverse()
    return final


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("run")
    parser.add_argument("--prepare-summary", required=True, help="prepare_summary.json generated by prepare_back_chin_merged_bag.py")
    parser.add_argument("--title", default="Back LIO + back/chin merged map, no tail")
    args = parser.parse_args()

    run = Path(args.run)
    prepare = load_prepare_summary(Path(args.prepare_summary))
    analysis = run.parent / "analysis"
    analysis.mkdir(exist_ok=True)
    log = (run / "run.log").read_text(errors="ignore")
    final = latest_pose_rows(log)
    xy = np.array([[p[1], p[2]] for p in final], dtype=float)
    path_length = float(np.linalg.norm(np.diff(xy, axis=0), axis=1).sum()) if len(xy) > 1 else 0.0
    closure = float(np.linalg.norm(xy[-1] - xy[0])) if len(xy) > 1 else 0.0
    span = xy.max(axis=0) - xy.min(axis=0) if len(xy) else np.array([0.0, 0.0])

    traj_csv = analysis / "back_chin_no_tail_keyframe_trajectory.csv"
    with traj_csv.open("w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["kf_id", "x", "y", "z"])
        writer.writerows(final)

    traj_png = analysis / "back_chin_no_tail_trajectory.png"
    if len(xy):
        plt.figure(figsize=(8, 7))
        plt.plot(xy[:, 0], xy[:, 1], lw=1.7)
        plt.scatter([xy[0, 0], xy[-1, 0]], [xy[0, 1], xy[-1, 1]], marker="x", s=40)
        plt.axis("equal")
        plt.grid(True, alpha=0.3)
        plt.xlabel("x m")
        plt.ylabel("y m")
        plt.title(args.title)
        plt.tight_layout()
        plt.savefig(traj_png, dpi=160)
        plt.close()

    map_dir = run / "data" / "new_map"
    arr = np.array(Image.open(map_dir / "map.pgm").convert("L"))
    map_png = analysis / "back_chin_no_tail_map_preview.png"
    Image.fromarray(np.dstack([arr, arr, arr])).save(map_png)

    source_lines = log.count("[split mapping source filter]")
    fallback = log.count("fallback to back-only")
    flush = re.findall(r"split mapping flush:.*stale_map=(\d+), deskew_no_trajectory=(\d+), back_only_fallback=(\d+)", log)
    flush_text = str(flush[-1]) if flush else "n/a"

    summary = f"""# {args.title}

Prepared bag:
- input bag: {prepare.get('input_bag')}
- output bag: {prepare.get('output_bag')}
- back cloud topic: {prepare['input_topics']['back_cloud']}
- chin cloud topic: {prepare['input_topics']['chin_cloud']}
- chin-in-back topic: {prepare['output_topics']['chin_in_back_cloud']}
- merged topic: {prepare['output_topics']['merged_cloud']}
- extrinsic: {prepare.get('extrinsic')}

Prepared counts:
- back frames: {prepare['back_frames']}
- chin frames: {prepare['chin_frames']}
- chin-in-back frames: {prepare['chin_in_back_frames']}
- merged frames: {prepare['merged_frames']}
- imu frames: {prepare['imu_frames']}
- matched chin frames: {prepare['matched_frames']}
- back-only merged frames: {prepare['back_only_frames']}
- source_id=1 points in merged: {prepare['source1_points_in_merged']}
- duplicate chin reuse: {prepare['duplicate_chin_reuse']}
- sync dt median: {prepare['dt_median_ms']} ms
- sync dt p95 abs: {prepare['dt_p95_abs_ms']} ms
- sync dt max abs: {prepare['dt_max_abs_ms']} ms

SLAM saved map metrics:
- keyframes: {len(final)}
- XY path length: {path_length:.3f} m
- XY closure displacement: {closure:.3f} m
- XY span: {float(span[0]):.3f} x {float(span[1]):.3f} m
- split mapping source-filter keyframes: {source_lines}
- back-only fallback count: {fallback}
- split flush: {flush_text}
- map image: {arr.shape[1]} x {arr.shape[0]}, occupied={int((arr < 10).sum())}, free={int((arr > 245).sum())}, unknown={int(((arr >= 10) & (arr <= 245)).sum())}

Files:
- map: {map_dir}
- map preview: {map_png}
- trajectory png: {traj_png}
- trajectory csv: {traj_csv}
"""
    out = analysis / "back_chin_no_tail_summary.md"
    out.write_text(summary)
    print(summary)


if __name__ == "__main__":
    main()
